export interface YouTubeStream {
  id: string
  channelId: string
  handle: string
  videoId?: string
  youtubeId?: string
  name: string
  region: string
  country: string
  language: string
  flag: string
  category: 'global' | 'mena' | 'asia' | 'southasia' |
            'africa' | 'europe' | 'americas' | 'defense' | 'eastasia'
  watchUrl: string
  embedDisabled?: boolean
}

export type NewsChannel = YouTubeStream

export interface WebcamSource {
  id: string
  name: string
  location?: string
  city?: string
  country: string
  flag: string
  region: string
  embedUrl: string
  type: 'youtube' | 'iframe'
  watchUrl: string
  videoId?: string
  lat: number
  lon: number
}

export type WebcamFeed = WebcamSource

export const YOUTUBE_STREAMS: YouTubeStream[] = [

  {
    id: 'aljazeera',
    channelId: 'UCNye-wNBqNL5ZzHSJdba5zA',
    handle: 'AlJazeeraEnglish',
    name: 'Al Jazeera English',
    region: 'Global', country: 'Qatar',
    language: 'EN', flag: '🇶🇦',
    category: 'global',
    watchUrl: 'https://www.youtube.com/@AlJazeeraEnglish/live',
  },
  {
    id: 'dw',
    channelId: 'UCknLrEdhRCp1aegoMqRaCZg',
    handle: 'DWNews',
    name: 'DW News',
    region: 'Global', country: 'Germany',
    language: 'EN', flag: '🇩🇪',
    category: 'global',
    watchUrl: 'https://www.youtube.com/@DWNews/live',
  },
  {
    id: 'france24',
    channelId: 'UCQfwfsi5VrQ8yKZ-UWmAoBg',
    handle: 'FRANCE24English',
    name: 'France 24 English',
    region: 'Global', country: 'France',
    language: 'EN', flag: '🇫🇷',
    category: 'global',
    watchUrl: 'https://www.youtube.com/@FRANCE24English/live',
  },
  {
    id: 'euronews',
    channelId: 'UCW2OZEnmkf8NuvuJRCrCuHg',
    handle: 'euronews',
    name: 'Euronews',
    region: 'Europe/Global', country: 'Belgium',
    language: 'EN', flag: '🇪🇺',
    category: 'global',
    watchUrl: 'https://www.youtube.com/@euronews/live',
  },
  {
    id: 'skynews',
    channelId: 'UCoMdktPbSTixAyNGwb-UYkQ',
    handle: 'SkyNews',
    name: 'Sky News',
    region: 'UK/Global', country: 'UK',
    language: 'EN', flag: '🇬🇧',
    category: 'global',
    watchUrl: 'https://www.youtube.com/@SkyNews/live',
  },
  {
    id: 'bloomberg',
    channelId: 'UCIALMKvObZNtJ6AmdCLP7Lg',
    handle: 'Bloomberg',
    name: 'Bloomberg TV',
    region: 'Finance/Global', country: 'USA',
    language: 'EN', flag: '🇺🇸',
    category: 'global',
    watchUrl: 'https://www.youtube.com/@Bloomberg/live',
  },
  {
    id: 'abcnews',
    channelId: 'UCBi2mrWuNuyYy4gbM6fU18Q',
    handle: 'ABCNews',
    name: 'ABC News',
    region: 'Americas/Global', country: 'USA',
    language: 'EN', flag: '🇺🇸',
    category: 'global',
    watchUrl: 'https://www.youtube.com/@ABCNews/live',
  },
  {
    id: 'nbcnews',
    channelId: 'UCeY0bbntWzzVIaj2z3QigXg',
    handle: 'NBCNews',
    name: 'NBC News',
    region: 'Americas', country: 'USA',
    language: 'EN', flag: '🇺🇸',
    category: 'americas',
    watchUrl: 'https://www.youtube.com/@NBCNews/live',
  },
  {
    id: 'nhkworld',
    channelId: 'UC6D3JNPdKHgPOMHLEWwNBrg',
    handle: 'NHKWorldNews',
    name: 'NHK World Japan',
    region: 'Japan/Asia', country: 'Japan',
    language: 'EN', flag: '🇯🇵',
    category: 'eastasia',
    watchUrl: 'https://www.youtube.com/@NHKWorldNews/live',
  },

  {
    id: 'trtworld',
    channelId: 'UC7_gcs09iThXybpVgjHZ_7g',
    handle: 'TRTWorld',
    name: 'TRT World',
    region: 'MENA/Global', country: 'Turkey',
    language: 'EN', flag: '🇹🇷',
    category: 'mena',
    watchUrl: 'https://www.youtube.com/@TRTWorld/live',
  },
  {
    id: 'iranintl',
    channelId: 'UCL0PNgCtFXrBc0mrOLBmWyw',
    handle: 'IranInternationalTV',
    name: 'Iran International',
    region: 'Iran/MENA', country: 'UK',
    language: 'FA/EN', flag: '🇮🇷',
    category: 'mena',
    watchUrl: 'https://www.youtube.com/@IranInternationalTV/live',
  },
  {
    id: 'i24news',
    channelId: 'UCFCldFME0sTwiVFlBSMbRiQ',
    handle: 'i24NEWS',
    name: 'i24 News (Israel)',
    region: 'Israel/MENA', country: 'Israel',
    language: 'EN', flag: '🇮🇱',
    category: 'mena',
    watchUrl: 'https://www.youtube.com/@i24NEWS/live',
  },
  {
    id: 'arabnews',
    channelId: 'UCF4Wxdo3inmxP-Y59wXDsFw',
    handle: 'ArabNewsTv',
    name: 'Arab News TV',
    region: 'MENA', country: 'Saudi Arabia',
    language: 'EN', flag: '🇸🇦',
    category: 'mena',
    watchUrl: 'https://www.youtube.com/@ArabNewsTv/live',
  },

  {
    id: 'wion',
    channelId: 'UCkAMNmzk6G7OKj4M5Dh3FHg',
    handle: 'wionews',
    name: 'WION',
    region: 'South Asia/Global', country: 'India',
    language: 'EN', flag: '🇮🇳',
    category: 'southasia',
    watchUrl: 'https://www.youtube.com/@wionews/live',
  },
  {
    id: 'timesnow',
    channelId: 'UCt4t-jeY85JegMlZ-E5UWtA',
    handle: 'TimesNow',
    name: 'Times Now',
    region: 'India', country: 'India',
    language: 'EN', flag: '🇮🇳',
    category: 'southasia',
    watchUrl: 'https://www.youtube.com/@TimesNow/live',
  },
  {
    id: 'ndtv',
    channelId: 'UCZFMm1mMw0F81Z37aaEzTUA',
    handle: 'ndtv',
    name: 'NDTV',
    region: 'India', country: 'India',
    language: 'EN', flag: '🇮🇳',
    category: 'southasia',
    watchUrl: 'https://www.youtube.com/@ndtv/live',
  },
  {
    id: 'geo',
    channelId: 'UCsT-y-cqkNMKlNLJgJ3b0jQ',
    handle: 'GeoNews',
    name: 'Geo News Pakistan',
    region: 'Pakistan', country: 'Pakistan',
    language: 'UR/EN', flag: '🇵🇰',
    category: 'southasia',
    watchUrl: 'https://www.youtube.com/@GeoNews/live',
  },
  {
    id: 'arynews',
    channelId: 'UCnNN8HCt_nOiQfSN3VPEFvw',
    handle: 'arynewsofficial',
    name: 'ARY News Pakistan',
    region: 'Pakistan', country: 'Pakistan',
    language: 'UR/EN', flag: '🇵🇰',
    category: 'southasia',
    watchUrl: 'https://www.youtube.com/@arynewsofficial/live',
  },
  {
    id: 'tolonews',
    channelId: 'UC-UqlBJe1FVbdQoFPqL2MBg',
    handle: 'TOLOnewsAfghanistan',
    name: 'TOLOnews Afghanistan',
    region: 'Afghanistan', country: 'Afghanistan',
    language: 'DA/PS', flag: '🇦🇫',
    category: 'southasia',
    watchUrl: 'https://www.youtube.com/@TOLOnewsAfghanistan/live',
  },

  {
    id: 'cna',
    channelId: 'UC3gBTRycsKRdXXOEJT8BZaQ',
    handle: 'ChannelNewsAsia',
    name: 'CNA Singapore',
    region: 'Southeast Asia', country: 'Singapore',
    language: 'EN', flag: '🇸🇬',
    category: 'eastasia',
    watchUrl: 'https://www.youtube.com/@ChannelNewsAsia/live',
  },
  {
    id: 'abcaustralia',
    channelId: 'UCVgO39Bk5sMo66-6o6Spn6Q',
    handle: 'abc',
    name: 'ABC News Australia',
    region: 'Oceania', country: 'Australia',
    language: 'EN', flag: '🇦🇺',
    category: 'eastasia',
    watchUrl: 'https://www.youtube.com/@abc/live',
  },
  {
    id: 'rfa',
    channelId: 'UCqBJ47FjJGCWnVkuVHLr7fQ',
    handle: 'RadioFreeAsia',
    name: 'Radio Free Asia',
    region: 'Asia (China/NK/Myanmar)', country: 'USA',
    language: 'EN', flag: '📡',
    category: 'eastasia',
    watchUrl: 'https://www.youtube.com/@RadioFreeAsia/live',
  },

  {
    id: 'africanews',
    channelId: 'UCG_abH9MSdADnMWxFjNYoAA',
    handle: 'africanews',
    name: 'Africanews',
    region: 'Africa', country: 'Pan-African',
    language: 'EN', flag: '🌍',
    category: 'africa',
    watchUrl: 'https://www.youtube.com/@africanews/live',
  },
  {
    id: 'channelstv',
    channelId: 'UCEXGDNclvMKGH_aYoOPgJ6Q',
    handle: 'ChannelsTv',
    name: 'Channels TV Nigeria',
    region: 'West Africa', country: 'Nigeria',
    language: 'EN', flag: '🇳🇬',
    category: 'africa',
    watchUrl: 'https://www.youtube.com/@ChannelsTv/live',
  },
  {
    id: 'sabcnews',
    channelId: 'UChLtXXpo4Ge9TX1lDFEtMxA',
    handle: 'SABCNews',
    name: 'SABC News South Africa',
    region: 'Southern Africa', country: 'South Africa',
    language: 'EN', flag: '🇿🇦',
    category: 'africa',
    watchUrl: 'https://www.youtube.com/@SABCNews/live',
  },

  {
    id: 'france24fr',
    channelId: 'UCD7AFo4NHMFkOoS3RcFCHBg',
    handle: 'France24fr',
    name: 'France 24 Français',
    region: 'Francophone', country: 'France',
    language: 'FR', flag: '🇫🇷',
    category: 'europe',
    watchUrl: 'https://www.youtube.com/@France24fr/live',
  },
  {
    id: 'euronewsru',
    channelId: 'UCHPGGGGHLgqrBmpFp-wP08g',
    handle: 'euronewsru',
    name: 'Euronews Russia',
    region: 'Russia/Europe', country: 'EU',
    language: 'RU', flag: '🇷🇺',
    category: 'europe',
    watchUrl: 'https://www.youtube.com/@euronewsru/live',
  },

  {
    id: 'telesur',
    channelId: 'UCNnMrqhqnlqPSLWFcf0QZUA',
    handle: 'telesurtvnews',
    name: 'teleSUR English',
    region: 'Latin America', country: 'Venezuela',
    language: 'EN', flag: '🌎',
    category: 'americas',
    watchUrl: 'https://www.youtube.com/@telesurtvnews/live',
  },
  {
    id: 'globalnews',
    channelId: 'UCx9TEHkQ-2hBDqCMoHNZkOg',
    handle: 'GlobalNews',
    name: 'Global News Canada',
    region: 'Canada', country: 'Canada',
    language: 'EN', flag: '🇨🇦',
    category: 'americas',
    watchUrl: 'https://www.youtube.com/@GlobalNews/live',
  },
]

export const WEBCAM_SOURCES: WebcamSource[] = [

  {
    id: 'dubai-marina',
    name: 'Dubai Marina',
    location: 'Dubai', country: 'UAE', flag: '🇦🇪',
    region: 'mena', lat: 25.080, lon: 55.140,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/united-arab-emirates/dubai/dubai/dubai-marina.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/united-arab-emirates/dubai/dubai/dubai-marina.html',
  },
  {
    id: 'mecca-haram',
    name: 'Masjid al-Haram',
    location: 'Mecca', country: 'Saudi Arabia', flag: '🇸🇦',
    region: 'mena', lat: 21.422, lon: 39.826,
    type: 'youtube',
    embedUrl: 'https://www.youtube.com/embed/live_stream?channel=UCkob4mWq7RX1rB3UhNJQmKg&autoplay=1&mute=1',
    watchUrl: 'https://www.youtube.com/@HaramainLive/live',
  },
  {
    id: 'istanbul-bosphorus',
    name: 'Bosphorus Strait',
    location: 'Istanbul', country: 'Turkey', flag: '🇹🇷',
    region: 'mena', lat: 41.009, lon: 28.977,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/turkiye/istanbul/istanbul/istanbul-bosphorus.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/turkiye/istanbul/istanbul/istanbul-bosphorus.html',
  },
  {
    id: 'cairo-nile',
    name: 'Cairo Nile View',
    location: 'Cairo', country: 'Egypt', flag: '🇪🇬',
    region: 'mena', lat: 30.044, lon: 31.235,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/egypt/cairo/cairo/cairo.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/egypt/cairo/cairo/cairo.html',
  },

  {
    id: 'mumbai-gateway',
    name: 'Gateway of India',
    location: 'Mumbai', country: 'India', flag: '🇮🇳',
    region: 'southasia', lat: 18.921, lon: 72.834,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/india/maharashtra/mumbai/gateway-india.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/india/maharashtra/mumbai/gateway-india.html',
  },
  {
    id: 'delhi-india-gate',
    name: 'India Gate, Delhi',
    location: 'New Delhi', country: 'India', flag: '🇮🇳',
    region: 'southasia', lat: 28.612, lon: 77.229,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/india/delhi/delhi/india-gate.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/india/delhi/delhi/india-gate.html',
  },

  {
    id: 'tokyo-shibuya',
    name: 'Shibuya Crossing',
    location: 'Tokyo', country: 'Japan', flag: '🇯🇵',
    region: 'eastasia', lat: 35.659, lon: 139.700,
    type: 'youtube',
    embedUrl: 'https://www.youtube.com/embed/live_stream?channel=UCPnkFMRx5zRMgcqCH8G-VNw&autoplay=1&mute=1',
    watchUrl: 'https://www.youtube.com/@ShibuyaSkyLive/live',
  },
  {
    id: 'taipei-101',
    name: 'Taipei 101',
    location: 'Taipei', country: 'Taiwan', flag: '🇹🇼',
    region: 'eastasia', lat: 25.033, lon: 121.565,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/taiwan/taipei/taipei/taipei.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/taiwan/taipei/taipei/taipei.html',
  },
  {
    id: 'hongkong-victoria',
    name: 'Victoria Harbour',
    location: 'Hong Kong', country: 'China', flag: '🇭🇰',
    region: 'eastasia', lat: 22.286, lon: 114.172,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/china/hong-kong/hong-kong/hong-kong.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/china/hong-kong/hong-kong/hong-kong.html',
  },
  {
    id: 'singapore-gardens',
    name: 'Gardens by the Bay',
    location: 'Singapore', country: 'Singapore', flag: '🇸🇬',
    region: 'eastasia', lat: 1.281, lon: 103.864,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/singapore/central/singapore/singapore.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/singapore/central/singapore/singapore.html',
  },

  {
    id: 'london-tower',
    name: 'Tower Bridge',
    location: 'London', country: 'UK', flag: '🇬🇧',
    region: 'europe', lat: 51.505, lon: -0.076,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/united-kingdom/england/london/tower-bridge.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/united-kingdom/england/london/tower-bridge.html',
  },
  {
    id: 'paris-eiffel',
    name: 'Eiffel Tower',
    location: 'Paris', country: 'France', flag: '🇫🇷',
    region: 'europe', lat: 48.858, lon: 2.294,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/france/ile-de-france/paris/eiffel-tower.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/france/ile-de-france/paris/eiffel-tower.html',
  },
  {
    id: 'rome-colosseum',
    name: 'Colosseum',
    location: 'Rome', country: 'Italy', flag: '🇮🇹',
    region: 'europe', lat: 41.890, lon: 12.492,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/italia/lazio/roma/colosseo.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/italia/lazio/roma/colosseo.html',
  },
  {
    id: 'kyiv-maidan',
    name: 'Maidan Square (Kyiv)',
    location: 'Kyiv', country: 'Ukraine', flag: '🇺🇦',
    region: 'europe', lat: 50.450, lon: 30.523,
    type: 'youtube',
    embedUrl: 'https://www.youtube.com/embed/live_stream?channel=UCbi2mrWuNuyYy4gbM6fU18Q&autoplay=1&mute=1',
    watchUrl: 'https://www.youtube.com/@KyivIndependent/live',
  },
  {
    id: 'berlin-brandgate',
    name: 'Brandenburg Gate',
    location: 'Berlin', country: 'Germany', flag: '🇩🇪',
    region: 'europe', lat: 52.516, lon: 13.377,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/germany/berlin/berlin/berlin.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/germany/berlin/berlin/berlin.html',
  },
  {
    id: 'madrid-puerta',
    name: 'Puerta del Sol',
    location: 'Madrid', country: 'Spain', flag: '🇪🇸',
    region: 'europe', lat: 40.416, lon: -3.703,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/puerta-del-sol.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/puerta-del-sol.html',
  },
  {
    id: 'amsterdam-canals',
    name: 'Amsterdam Canals',
    location: 'Amsterdam', country: 'Netherlands', flag: '🇳🇱',
    region: 'europe', lat: 52.370, lon: 4.895,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/nederland/noord-holland/amsterdam/amsterdam.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/nederland/noord-holland/amsterdam/amsterdam.html',
  },

  {
    id: 'capetown-tablemtn',
    name: 'Table Mountain',
    location: 'Cape Town', country: 'South Africa', flag: '🇿🇦',
    region: 'africa', lat: -33.963, lon: 18.410,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/south-africa/western-cape/cape-town/table-mountain.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/south-africa/western-cape/cape-town/table-mountain.html',
  },
  {
    id: 'nairobi-city',
    name: 'Nairobi City',
    location: 'Nairobi', country: 'Kenya', flag: '🇰🇪',
    region: 'africa', lat: -1.286, lon: 36.817,
    type: 'youtube',
    embedUrl: 'https://www.youtube.com/embed/live_stream?channel=UCEXGDNclvMKGH_aYoOPgJ6Q&autoplay=1&mute=1',
    watchUrl: 'https://www.youtube.com/@ChannelsTv/live',
  },

  {
    id: 'nyc-timessquare',
    name: 'Times Square',
    location: 'New York', country: 'USA', flag: '🇺🇸',
    region: 'americas', lat: 40.758, lon: -73.985,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york-city/times-square.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york-city/times-square.html',
  },
  {
    id: 'miami-ocean',
    name: 'Miami South Beach',
    location: 'Miami', country: 'USA', flag: '🇺🇸',
    region: 'americas', lat: 25.790, lon: -80.130,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/miami/miami-beach.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/miami/miami-beach.html',
  },
  {
    id: 'niagara-falls',
    name: 'Niagara Falls',
    location: 'Niagara', country: 'USA/Canada', flag: '🇺🇸',
    region: 'americas', lat: 43.082, lon: -79.074,
    type: 'youtube',
    embedUrl: 'https://www.youtube.com/embed/live_stream?channel=UCx9TEHkQ-2hBDqCMoHNZkOg&autoplay=1&mute=1',
    watchUrl: 'https://www.youtube.com/@GlobalNews/live',
  },

  {
    id: 'sydney-harbour',
    name: 'Sydney Harbour Bridge',
    location: 'Sydney', country: 'Australia', flag: '🇦🇺',
    region: 'oceania', lat: -33.852, lon: 151.210,
    type: 'iframe',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/australia/new-south-wales/sydney/sydney.html',
    watchUrl: 'https://www.skylinewebcams.com/en/webcam/australia/new-south-wales/sydney/sydney.html',
  },
]

export const STREAM_REGIONS = [
  { id: 'all',       label: 'All',        flag: '🌍' },
  { id: 'global',    label: 'Global',     flag: '📡' },
  { id: 'mena',      label: 'MENA',       flag: '🕌' },
  { id: 'southasia', label: 'S.Asia',     flag: '🇮🇳' },
  { id: 'eastasia',  label: 'E.Asia',     flag: '🏯' },
  { id: 'europe',    label: 'Europe',     flag: '🇪🇺' },
  { id: 'africa',    label: 'Africa',     flag: '🌍' },
  { id: 'americas',  label: 'Americas',   flag: '🌎' },
  { id: 'defense',   label: 'Defense',    flag: '🎖' },
] as const

export type StreamRegion = typeof STREAM_REGIONS[number]['id']

export const WEBCAM_REGIONS = [
  { id: 'all',       label: '🌍 All' },
  { id: 'mena',      label: '🕌 MENA' },
  { id: 'southasia', label: '🇮🇳 S.Asia' },
  { id: 'eastasia',  label: '🏯 E.Asia' },
  { id: 'europe',    label: '🇪🇺 Europe' },
  { id: 'africa',    label: '🌍 Africa' },
  { id: 'americas',  label: '🌎 Americas' },
  { id: 'oceania',   label: '🦘 Oceania' },
  { id: 'space',     label: '🚀 Space' },
]

export const NEWS_CHANNELS = YOUTUBE_STREAMS.map(s => ({
  ...s,
  youtubeId: s.videoId,
  city: s.region,
}))

export const WEBCAM_FEEDS: WebcamFeed[] = [

  {
    id: 'iran-tehran',
    name: 'Tehran Live',
    city: 'Tehran', country: 'Iran', flag: '🇮🇷',
    region: 'mena', lat: 35.689, lon: 51.388,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=-zGuR1qVKrU',
    videoId: '-zGuR1qVKrU',
  },
  {
    id: 'iran-telaviv',
    name: 'Tel Aviv Live',
    city: 'Tel Aviv', country: 'Israel', flag: '🇮🇱',
    region: 'mena', lat: 32.085, lon: 34.781,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=gmtlJ_m2r5A',
    videoId: 'gmtlJ_m2r5A',
  },
  {
    id: 'iran-jerusalem',
    name: 'Jerusalem Live',
    city: 'Jerusalem', country: 'Israel', flag: '🇮🇱',
    region: 'mena', lat: 31.776, lon: 35.235,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=fIurYTprwzg',
    videoId: 'fIurYTprwzg',
  },
  {
    id: 'western-wall',
    name: 'Western Wall',
    city: 'Jerusalem', country: 'Israel', flag: '🇮🇱',
    region: 'mena', lat: 31.776, lon: 35.234,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=UyduhBUpO7Q',
    videoId: 'UyduhBUpO7Q',
  },
  {
    id: 'mecca',
    name: 'Masjid al-Haram',
    city: 'Mecca', country: 'Saudi Arabia', flag: '🇸🇦',
    region: 'mena', lat: 21.422, lon: 39.826,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=Cm1v4bteXbI',
    videoId: 'Cm1v4bteXbI',
  },
  {
    id: 'beirut',
    name: 'Beirut Live',
    city: 'Beirut', country: 'Lebanon', flag: '🇱🇧',
    region: 'mena', lat: 33.888, lon: 35.495,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=djF-Lkgfp6k',
    videoId: 'djF-Lkgfp6k',
  },
  {
    id: 'mideast-multi',
    name: 'Middle East Multi',
    city: 'Middle East', country: 'Multi', flag: '🌍',
    region: 'mena', lat: 30.0, lon: 40.0,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=4E-iFtUM2kk',
    videoId: '4E-iFtUM2kk',
  },

  {
    id: 'kyiv',
    name: 'Kyiv Live',
    city: 'Kyiv', country: 'Ukraine', flag: '🇺🇦',
    region: 'europe', lat: 50.450, lon: 30.523,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=-Q7FuPINDjA',
    videoId: '-Q7FuPINDjA',
  },
  {
    id: 'odessa',
    name: 'Odessa Live',
    city: 'Odessa', country: 'Ukraine', flag: '🇺🇦',
    region: 'europe', lat: 46.477, lon: 30.732,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=e2gC37ILQmk',
    videoId: 'e2gC37ILQmk',
  },
  {
    id: 'paris',
    name: 'Paris Live',
    city: 'Paris', country: 'France', flag: '🇫🇷',
    region: 'europe', lat: 48.858, lon: 2.294,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=OzYp4NRZlwQ',
    videoId: 'OzYp4NRZlwQ',
  },
  {
    id: 'st-petersburg',
    name: 'St. Petersburg',
    city: 'St. Petersburg', country: 'Russia', flag: '🇷🇺',
    region: 'europe', lat: 59.950, lon: 30.316,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=CjtIYbmVfck',
    videoId: 'CjtIYbmVfck',
  },
  {
    id: 'london',
    name: 'London EarthCam',
    city: 'London', country: 'UK', flag: '🇬🇧',
    region: 'europe', lat: 51.505, lon: -0.076,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=Lxqcg1qt0XU',
    videoId: 'Lxqcg1qt0XU',
  },

  {
    id: 'washington-dc',
    name: 'Washington DC',
    city: 'Washington DC', country: 'USA', flag: '🇺🇸',
    region: 'americas', lat: 38.895, lon: -77.036,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=1wV9lLe14aU',
    videoId: '1wV9lLe14aU',
  },
  {
    id: 'new-york',
    name: 'New York EarthCam',
    city: 'New York', country: 'USA', flag: '🇺🇸',
    region: 'americas', lat: 40.758, lon: -73.985,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=4qyZLflp-sI',
    videoId: '4qyZLflp-sI',
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles Live',
    city: 'Los Angeles', country: 'USA', flag: '🇺🇸',
    region: 'americas', lat: 34.018, lon: -118.494,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=EO_1LWqsCNE',
    videoId: 'EO_1LWqsCNE',
  },
  {
    id: 'miami',
    name: 'Miami Beach Live',
    city: 'Miami', country: 'USA', flag: '🇺🇸',
    region: 'americas', lat: 25.790, lon: -80.130,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=5YCajRjvWCg',
    videoId: '5YCajRjvWCg',
  },

  {
    id: 'taipei',
    name: 'Taipei Live',
    city: 'Taipei', country: 'Taiwan', flag: '🇹🇼',
    region: 'eastasia', lat: 25.033, lon: 121.565,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=z_fY1pj1VBw',
    videoId: 'z_fY1pj1VBw',
  },
  {
    id: 'shanghai',
    name: 'Shanghai Live',
    city: 'Shanghai', country: 'China', flag: '🇨🇳',
    region: 'eastasia', lat: 31.224, lon: 121.469,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=76EwqI5XZIc',
    videoId: '76EwqI5XZIc',
  },
  {
    id: 'tokyo',
    name: 'Tokyo 4K Live',
    city: 'Tokyo', country: 'Japan', flag: '🇯🇵',
    region: 'eastasia', lat: 35.659, lon: 139.700,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=4pu9sF5Qssw',
    videoId: '4pu9sF5Qssw',
  },
  {
    id: 'seoul',
    name: 'Seoul Live',
    city: 'Seoul', country: 'South Korea', flag: '🇰🇷',
    region: 'eastasia', lat: 37.566, lon: 126.977,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=-JhoMGoAfFc',
    videoId: '-JhoMGoAfFc',
  },
  {
    id: 'sydney',
    name: 'Sydney Webcam',
    city: 'Sydney', country: 'Australia', flag: '🇦🇺',
    region: 'oceania', lat: -33.852, lon: 151.210,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=7pcL-0Wo77U',
    videoId: '7pcL-0Wo77U',
  },

  {
    id: 'iss-earth',
    name: 'ISS Earth View',
    city: 'ISS Earth View', country: 'Space', flag: '🛸',
    region: 'space', lat: 0, lon: 0,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=vytmBNhc9ig',
    videoId: 'vytmBNhc9ig',
  },
  {
    id: 'nasa-tv',
    name: 'NASA TV Live',
    city: 'NASA TV', country: 'Space', flag: '🚀',
    region: 'space', lat: 0, lon: 0,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=zPH5KtjJFaQ',
    videoId: 'zPH5KtjJFaQ',
  },
  {
    id: 'space-walk',
    name: 'NASA Space Walk',
    city: 'Space Walk', country: 'Space', flag: '👨‍🚀',
    region: 'space', lat: 0, lon: 0,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=0FBiyFpV__g',
    videoId: '0FBiyFpV__g',
  },
  {
    id: 'spacex',
    name: 'SpaceX Live',
    city: 'SpaceX', country: 'Space', flag: '🚀',
    region: 'space', lat: 0, lon: 0,
    type: 'youtube',
    embedUrl: '',
    watchUrl: 'https://www.youtube.com/watch?v=fO9e9jnhYK8',
    videoId: 'fO9e9jnhYK8',
  },
]
